apiVersion: v1
kind: Service
metadata:
  name: backend-backend-headless
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  clusterIP: None
    # publishNotReadyAddresses: true
  selector:
    # {{- include "backend.selectorLabels" . | nindent 4 }}
    app: backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000