global:
  imageRegistry: public.ecr.aws   # prefixes all Bitnami images

mongodb:
  image:
    repository: bitnami/mongodb   # becomes public.ecr.aws/bitnami/mongodb
    tag: latest
    pullPolicy: Always

  architecture: replicaset
  replicaCount: 2
  
  arbiter:
    enabled: false

  auth:
    enabled: false
  persistence:
    size: 10Gi
