global:
  imageRegistry: public.ecr.aws   # prefixes all Bitnami images

mongodb:
  image:
    repository: bitnami/mongodb   # becomes public.ecr.aws/bitnami/mongodb
    tag: latest
    pullPolicy: Always

  architecture: replicaset
<<<<<<< HEAD
  replicaCount: 3
=======
  replicaCount: 2
>>>>>>> 9203ec862771d700914cee90c24eabaf48ecc90f
  
  arbiter:
    enabled: false

  auth:
    enabled: false
  persistence:
    size: 10Gi
