backend:
  replicas: 1

  image:
    repository: ajaykumarchoda8143/backend
    tag: v17
    pullPolicy: IfNotPresent

  service:
    type: LoadBalancer
    port: 3000

  env:
    FRONTEND_ORIGIN: "http://52.151.203.181"
    MONGO_URL: "mongodb://mongodb-mongodb-0.mongodb-mongodb-headless.default.svc.cluster.local:27017,mongodb-mongodb-1.mongodb-mongodb-headless.default.svc.cluster.local:27017,mongodb-mongodb-2.mongodb-mongodb-headless.default.svc.cluster.local:27017/?replicaSet=rs0"


  storage:
  size: 1Gi
  accessMode: ReadWriteOnce          
  storageClassName: default   
  reclaimPolicy: Delete
  lifecycleMode: Dynamic       
  mountPath: /app/data
    
  topologySpread:
    enabled: false
    
  probes:
    readiness:
      path: /health
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 3
    liveness:
      path: /health
      initialDelaySeconds: 10
      periodSeconds: 15
      timeoutSeconds: 2
      failureThreshold: 3

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  podSecurityContext:
    runAsNonRoot: true
    fsGroup: 1000
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    readOnlyRootFilesystem: false

  # resources: {}

  # persistence:
  #   enabled: true
  #   mountPath: /data
  #   accessModes:
  #     - ReadWriteOnce
  #   size: 1Gi
  #   storageClassName: default



